import type { Metadata } from "next";
import Link from "next/link";
import {
  Agreement02Icon,
  Alert02Icon,
  CopyrightIcon,
  RefreshIcon,
  Shield01Icon,
  SparklesIcon,
  UserIcon,
} from "@hugeicons/core-free-icons";
import { Clause, LegalPage } from "@/components/legal-page";

export const metadata: Metadata = {
  title: "Terms of use",
  description: "The plain-language terms for using wordseed, a student-built sentence generator.",
  alternates: { canonical: "/terms" },
};

export default function TermsPage() {
  return (
    <LegalPage
      icon={Agreement02Icon}
      title="Terms of use"
      intro="The short version: wordseed is a free student project for learning and fun. The sentences are written by a machine from old books and Wikipedia, so treat them as playful experiments, not facts."
      updated="4 October 2026"
      other={{ href: "/privacy", label: "Privacy & cookies" }}
    >
      <Clause icon={SparklesIcon} title="What wordseed is">
        <p>
          wordseed is a college NLP project that writes sentences containing a word you choose, using language models
          built from scratch. It is free to use, has no accounts, and its code is open source under the MIT licence on{" "}
          <a href="https://github.com/TrendySloth1001/wordseed" className="underline underline-offset-4">
            GitHub
          </a>
          . By generating sentences you agree to these terms; if you do not agree, please do not use it.
        </p>
      </Clause>

      <Clause icon={Alert02Icon} title="About the sentences">
        <ul>
          <li>
            They are machine-generated by recombining phrases from 17 public-domain novels and Simple English
            Wikipedia. They can be wrong, nonsensical, outdated or offensive: old books reflect the attitudes of their
            time.
          </li>
          <li>They are not facts, advice or anyone&apos;s opinion. Please don&apos;t rely on them for anything important.</li>
          <li>
            You are responsible for how you use what you generate. Don&apos;t present it as written by a person or as
            accurate information when it isn&apos;t.
          </li>
        </ul>
      </Clause>

      <Clause icon={Shield01Icon} title="Fair use of the service">
        <ul>
          <li>Use it at a human pace. Requests are rate-limited per visitor, and automated hammering is blocked.</li>
          <li>Don&apos;t try to break, overload or attack the site, or use it to create spam.</li>
          <li>Access may be limited or blocked for anyone who misuses it.</li>
        </ul>
      </Clause>

      <Clause icon={CopyrightIcon} title="Content and licences">
        <ul>
          <li>The novels come from Project Gutenberg and are in the public domain in the United States.</li>
          <li>
            Simple English Wikipedia text is licensed CC BY-SA 4.0. Generated sentences can contain short stretches of
            it; if you republish them, crediting Wikipedia is the right thing to do.
          </li>
          <li>The code is MIT-licensed. Diagrams in the docs are credited where they appear.</li>
          <li>You can use the sentences you generate however you like, within the above.</li>
        </ul>
      </Clause>

      <Clause icon={UserIcon} title="No warranty">
        <p>
          wordseed is provided &ldquo;as is&rdquo;, without any warranty, by a student, for learning. It may be
          unavailable, change or stop at any time. To the extent the law allows, its author is not liable for any loss
          or harm arising from using it or its output.
        </p>
      </Clause>

      <Clause icon={RefreshIcon} title="Changes">
        <p>
          If these terms change in a way that matters, you will be asked to agree again before generating. How your
          data is handled is described in{" "}
          <Link href="/privacy" className="underline underline-offset-4">
            Privacy &amp; cookies
          </Link>
          . Questions: open an issue on GitHub.
        </p>
      </Clause>
    </LegalPage>
  );
}
